import type { AppState, Process } from '../types'

export function generateReport(D: AppState): string {
  const c = D.company
  const ds = D.departments
  const vs = D.vendors
  const tk = D.tasks
  const rs = D.assessments
  const cd = D.critDates
  const allP: (Process & { dept?: string })[] = ds.flatMap(d => d.processes.map(p => ({ ...p, dept: d.name })))
  const ps = {
    sd: allP.filter(p => p.rto === 'Same Day'),
    d1: allP.filter(p => p.rto === '1 Day'),
    d25: allP.filter(p => p.rto === '2-5 Days'),
    d6: allP.filter(p => p.rto === '6+ Days'),
  }

  let r = `${'═'.repeat(60)}\n${c.name.toUpperCase()}\nBUSINESS CONTINUITY PLAN\nGenerated by Bedrock | ${new Date().toLocaleDateString()} | CONFIDENTIAL\n${'═'.repeat(60)}\n\n`
  r += `TABLE OF CONTENTS\n${'─'.repeat(44)}\n`
  ;["1. General Planning", "2. Team Structure", "3. Plan Activation", "4. Processes by RTO", "5. Critical Dates", "6. MTDs", "7. Continuity Tasks", "8. Risk Assessments", "9. BIA", "10. Incident History", "11-17. Appendices"].forEach(s => r += `  ${s}\n`)

  r += `\n${'═'.repeat(60)}\n1. GENERAL PLANNING\n${'═'.repeat(60)}\n\nBCP for ${c.name} at ${c.addr}, ${c.city}, ${c.state}. ${D.locations.length} facilities, ${D.users.length} key personnel.\n`
  r += `Recovery: Same Day: ${ps.sd.length} | 1 Day: ${ps.d1.length} | 2-5 Days: ${ps.d25.length} | 6+ Days: ${ps.d6.length}\n\n`

  r += `${'═'.repeat(60)}\n2. TEAM STRUCTURE\n${'═'.repeat(60)}\n\n`
  D.users.filter(u => u.role === 'admin' || u.role === 'program_manager').forEach(u => {
    r += `  ${u.fn} ${u.ln} - ${u.title}\n  ${u.email} | ${u.phone}\n\n`
  })
  r += `Department Leads:\n`
  ds.forEach(d => {
    const l = D.users.find(u => u.id === d.lead)
    r += `  ${d.name}: ${l ? `${l.fn} ${l.ln}` : '-'}\n`
  })

  r += `\n${'═'.repeat(60)}\n3. PLAN ACTIVATION\n${'═'.repeat(60)}\n\n  Level 1 (MONITOR) | Level 2 (ALERT) | Level 3 (ACTIVATE)\n\n`

  r += `${'═'.repeat(60)}\n4. PROCESSES BY RTO\n${'═'.repeat(60)}\n\n`
  const rtoG: Record<string, (Process & { dept?: string })[]> = { "Same Day": [], "1 Day": [], "2-5 Days": [], "6+ Days": [] }
  ds.forEach(d => d.processes.forEach(p => {
    if (rtoG[p.rto]) rtoG[p.rto].push({ ...p, dept: d.name })
  }))
  Object.entries(rtoG).forEach(([rto, procs]) => {
    r += `── ${rto} (${procs.length}) ──\n`
    procs.forEach(p => {
      r += `  ${p.name} [${p.pri}] ${p.status}\n  ${p.dept} | RPO: ${p.rpo} | MTD: ${p.mtd} | Strategy: ${p.strat || 'TBD'}\n\n`
    })
  })

  r += `${'═'.repeat(60)}\n5. CRITICAL DATES\n${'═'.repeat(60)}\n\n`
  cd.forEach(d => { r += `  ${d.date} — ${d.name} (${d.dept})\n` })

  r += `\n${'═'.repeat(60)}\n7. CONTINUITY TASKS\n${'═'.repeat(60)}\n\n`
  const phases: [string, string[]][] = [['Early Closure', tk.early], ['0-24 Hours', tk.immed], ['2-5 Days', tk.short], ['6+ Days', tk.long]]
  phases.forEach(([t, tasks]) => {
    r += `── ${t} ──\n`
    tasks.forEach((task, i) => r += `  ${i + 1}. ${task}\n`)
    r += '\n'
  })

  r += `${'═'.repeat(60)}\n8. RISK ASSESSMENTS\n${'═'.repeat(60)}\n\n`
  rs.forEach(a => {
    r += `  ${a.name} [${a.status}] L:${a.like} I:${a.impact} RPN:${a.rpn}\n  Mitigations: ${a.miti}\n\n`
  })

  r += `${'═'.repeat(60)}\nAPPENDICES\n${'═'.repeat(60)}\n\nA. Vendors:\n`
  vs.forEach(v => {
    r += `  ${v.name} ${v.critical ? '★' : ''} | SLA: ${v.sla} | ${v.contact} | ${v.phone}\n`
  })
  r += `\nB. Technologies:\n`
  D.technologies.forEach(t => {
    r += `  ${t.name} | ${t.tier} | ${t.type} | RPO: ${t.rpo}\n`
  })
  r += `\nC. Personnel:\n`
  D.users.forEach(u => {
    r += `  ${u.fn} ${u.ln} - ${u.title} | ${u.email}\n`
  })
  r += `\n${'═'.repeat(60)}\nEND OF PLAN — Generated by Bedrock\n${'═'.repeat(60)}`
  return r
}
